'use strict';
(() => {
 const root=document.documentElement, reduced=matchMedia('(prefers-reduced-motion: reduce)'), motion=document.querySelector('.motion-toggle');
 let preference=null; try{preference=localStorage.getItem('risa-quest-motion');}catch(_){}
 let paused=preference==='paused'||(preference!=='playing'&&reduced.matches);
 function applyMotion(){root.classList.toggle('motion-paused',paused);if(motion){motion.setAttribute('aria-pressed',String(paused));motion.setAttribute('aria-label',paused?'アニメーションを再開する':'アニメーションを停止する');motion.innerHTML=`<span aria-hidden="true">${paused?'▷':'Ⅱ'}</span><span class="motion-label">${paused?'動きを再開':'動きを止める'}</span>`;}if(paused||reduced.matches)document.querySelectorAll('.is-pending').forEach(el=>{el.classList.remove('is-pending');el.classList.add('is-visible');});}
 applyMotion();motion?.addEventListener('click',()=>{paused=!paused;preference=paused?'paused':'playing';try{localStorage.setItem('risa-quest-motion',preference);}catch(_){}applyMotion();});reduced.addEventListener('change',()=>{if(preference===null)paused=reduced.matches;applyMotion();});
 const menu=document.querySelector('.menu-toggle'), mobileNav=document.querySelector('#mobile-nav');
 function closeMenu(){if(!menu||!mobileNav)return;menu.setAttribute('aria-expanded','false');mobileNav.hidden=true;}
 menu?.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));mobileNav.hidden=!open;});mobileNav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&menu?.getAttribute('aria-expanded')==='true'){closeMenu();menu.focus();}});matchMedia('(min-width:761px)').addEventListener('change',e=>{if(e.matches)closeMenu();});
 const reveals=document.querySelectorAll('.reveal');
 if('IntersectionObserver' in window&&!paused&&!reduced.matches){const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.remove('is-pending');e.target.classList.add('is-visible');io.unobserve(e.target);}}),{threshold:.03,rootMargin:'0px 0px -25px 0px'});reveals.forEach(el=>{if(el.getBoundingClientRect().top>innerHeight){el.classList.add('is-pending');io.observe(el);}else el.classList.add('is-visible');});document.addEventListener('focusin',e=>{const el=e.target.closest('.is-pending');if(el){el.classList.remove('is-pending');el.classList.add('is-visible');}});addEventListener('beforeprint',()=>reveals.forEach(el=>el.classList.remove('is-pending')));}
 function revealHash(){let target;try{target=document.getElementById(decodeURIComponent(location.hash.slice(1)));}catch(_){return;}if(target)[target,...target.querySelectorAll('.is-pending')].forEach(el=>{el.classList.remove('is-pending');el.classList.add('is-visible');});}
 addEventListener('hashchange',revealHash);revealHash();
 const navLinks=document.querySelectorAll('.desktop-nav a');
 if('IntersectionObserver' in window){const scene=document.querySelector('.world-scene');if(scene)new IntersectionObserver(entries=>entries.forEach(e=>root.classList.toggle('scene-offscreen',!e.isIntersecting))).observe(scene);const ci=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)navLinks.forEach(a=>{if(a.hash==='#'+e.target.id)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current');});}),{rootMargin:'-10% 0px -65% 0px',threshold:0});document.querySelectorAll('main>.chapter').forEach(el=>ci.observe(el));}
 const back=document.querySelector('.back-map');let scheduled=false;function update(){back?.classList.toggle('visible',scrollY>650);scheduled=false;}addEventListener('scroll',()=>{if(!scheduled){scheduled=true;requestAnimationFrame(update);}},{passive:true});update();
})();
